export interface MissionModel{
    // missionsTitle :string,
    missionsTitle1 : string,
    missionsTitle2 : string,
    missionsTitle3 : string,
    missionsTitle4 : string,
    missionsTitle5 : string,
    missionsTitle6 : string,
    // missionsObj1:{missionsDesc1:string},
    // missionsObj2:{missionsDesc2:string},
    // missionsObj3:{missionsDesc3:string},
    // missionsObj4:{missionsDesc4:string},
    // missionsObj5:{missionsDesc5:string},
    // missionsObj6:{missionsDesc6:string},
    missionsDesc : string,
    missionsIconsPath :string,
    cmsHomeID:string,
    missionsID:string
    missionsID1:'',
    missionsID2:'',
    missionsID3:'',
    missionsID4:'',
    missionsID5:'',
    missionsID6 :'',
}